# Generated by Django 4.2.11 on 2024-12-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('address', models.CharField(max_length=55)),
                ('salary', models.FloatField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
