# Generated by Django 4.2.11 on 2024-12-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
